services:
  - type: web
    name: conquista-cajas-1vs1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:socket_app --host 0.0.0.0 --port $PORT
